Arena:
  players: 2
  name: "Test arena"
  world: "world"
  spawn: "34 77 -323"
  locations:
    - "34 77 -323"
    - "35 78 -322"
    - "36 79 -320"
    - "37 80 -319"
  bounds:
    - pos1: "34 77 -323"
      pos2: "37 80 -319"
    - pos1: "34 77 -323"
      pos2: "37 80 -319"
  cascade:
    first: 1
    second:
      dog:
        paw: "Paw"
        body: "Body"
      cat: "Snuggles"
  empty: []
  block: STONE